version: "3.9"

# services:
# db:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   platform: linux/x86_64
#   image: mysql:5.7
#   container_name: db-mysql
#   restart: always
#   environment:
#     - MYSQL_ROOT_PASSWORD=password
#     - MYSQL_DATABASE=db
#     - MYSQL_USER=user
#     - MYSQL_PASSWORD=password
#     - MYSQL_TCP_PORT=3307
#   ports: [3307:3307]
#   expose:
#     - 3307
#   volumes:
#     - ./init:/docker-entrypoint-initdb.d
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - .env
    ports: [8090:8090]
    expose: [8090]
    environment:
      - DEVELOPMENT_DB_HOST=localhost
    command: npm run start-production
    networks:
      - appNet

networks:
  appNet:
    driver: bridge
